language: elixir
elixir: 1.3.0
otp_release:
  - 18.3
sudo: false
env:
  - MIX_ENV=test
addons:
  postgresql: '9.4'
services:
  - postgresql
before_script:
  - cp config/travis.exs config/test.exs
  - MIX_ENV=test mix do ecto.create, ecto.migrate
  - MIX_ENV=test mix local.hex --force
  - MIX_ENV=test mix deps.get
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
script:
  - mix test
after_script:
  - mix coveralls.travis
