language: elixir
elixir: 1.2.0
otp_release:
  - 18.1
sudo: false
before_script:
  - cp config/dev.secret.example.exs config/dev.secret.exs
  - mix local.hex --force
  - mix deps.get
script:
  - mix test
